name: infer_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  crypto: ^3.0.7
  device_info_plus: ^13.2.0
  file_picker: any
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_painter_v2: 2.1.0+1
  http: ^1.6.0
  package_info_plus: ^10.2.1
  pub_semver: ^2.2.0
  shared_preferences: ^2.5.5
  uuid: ^4.6.0
  window_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
